version: "3.9"
services:
  mumble-server:
    container_name: mumble-server
    image: mumblevoip/mumble-server:v1.5.735-0
    restart: unless-stopped
    hostname: mumble-server
    environment:
      - TZ=${TZ}
      - MAX_USERS=500
    volumes:
      - ${APP_DATA_DIR}/data/mumble/config:/data
    ports:
      - ${APP_PORT}:64738
      - ${APP_PORT_UDP}:64738/udp
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.mumble-web-redirect.redirectscheme.scheme: https
      traefik.http.services.mumble.loadbalancer.server.port: 64738
      # Web
      traefik.http.routers.mumble-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mumble-insecure.entrypoints: web
      traefik.http.routers.mumble-insecure.service: mumble
      traefik.http.routers.mumble-insecure.middlewares: mumble-web-redirect
      # Websecure
      traefik.http.routers.mumble.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mumble.entrypoints: websecure
      traefik.http.routers.mumble.service: mumble
      traefik.http.routers.mumble.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.mumble-local-insecure.rule: Host(`mumble.${LOCAL_DOMAIN}`)
      traefik.http.routers.mumble-local-insecure.entrypoints: web
      traefik.http.routers.mumble-local-insecure.service: mumble
      traefik.http.routers.mumble-local-insecure.middlewares: mumble-web-redirect
      # Local domain secure
      traefik.http.routers.mumble-local.rule: Host(`mumble.${LOCAL_DOMAIN}`)
      traefik.http.routers.mumble-local.entrypoints: websecure
      traefik.http.routers.mumble-local.service: mumble
      traefik.http.routers.mumble-local.tls: true
networks:
  tipi_main_network:
    external: true
